package com.example.assignment3;

public class StudentsData {

    public static String[] rollNo = new String[]{
            "MT20116",
            "MT20117",
            "MT20118",
            "MT20119",
            "MT20120",
            "MT20121",
            "MT20122",
            "MT20123",
            "MT20124",
            "MT20125",
            "MT20126",
            "MT20127",
            "MT20128",
            "MT20129",
            "MT20130",
            "MT20131",
            "MT20132",
            "MT20133",
            "MT20134",
            "MT20135",
            "MT20136",
            "MT20137",
            "MT20138",
            "MT20139",
            "MT20140",
            "MT20141",
            "MT20142",
            "MT20143",
            "MT20144",
            "MT20145"
    };

    public static String[] name = new String[]{
            "James",
            "John",
            "Robert",
            "Michael",
            "Charles",
            "Victoria",
            "Steven",
            "Rose",
            "Matthew",
            "Andrew",
            "Shira",
            "Alice",
            "Linnea",
            "Anika",
            "Ronald",
            "Jason",
            "Amelie",
            "Alessia",
            "Amaia",
            "Jaffrey",
            "Bella",
            "harmaini",
            "Jacob",
            "Eric",
            "Justin",
            "Frank",
            "Jack",
            "Bob",
            "Molly",
            "Winky"
    };

    public static int[] id = new int[]{
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person,
            R.drawable.person
    };

    public static String[] branch = new String[]{
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Data Science",
            "Data Science",
            "Data Science",
            "Data Science",
            "Data Science",
            "Data Science",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Artificial Intelligence",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Mobile Computing",
            "Data Science",
            "Data Science",
    };

    public static String[] email = new String[]{
            "MT20116@iiitd.ac.in",
            "MT20117@iiitd.ac.in",
            "MT20118@iiitd.ac.in",
            "MT20119@iiitd.ac.in",
            "MT20120@iiitd.ac.in",
            "MT20121@iiitd.ac.in",
            "MT20122@iiitd.ac.in",
            "MT20123@iiitd.ac.in",
            "MT20124@iiitd.ac.in",
            "MT20125@iiitd.ac.in",
            "MT20126@iiitd.ac.in",
            "MT20127@iiitd.ac.in",
            "MT20128@iiitd.ac.in",
            "MT20129@iiitd.ac.in",
            "MT20130@iiitd.ac.in",
            "MT20131@iiitd.ac.in",
            "MT20132@iiitd.ac.in",
            "MT20133@iiitd.ac.in",
            "MT20134@iiitd.ac.in",
            "MT20135@iiitd.ac.in",
            "MT20136@iiitd.ac.in",
            "MT20137@iiitd.ac.in",
            "MT20138@iiitd.ac.in",
            "MT20139@iiitd.ac.in",
            "MT20140@iiitd.ac.in",
            "MT20141@iiitd.ac.in",
            "MT20142@iiitd.ac.in",
            "MT20143@iiitd.ac.in",
            "MT20144@iiitd.ac.in",
            "MT20145@iiitd.ac.in"
    };

    public static String[] phoneNo = new String[]{
            "+91 61279 47680",
            "+91 80796 66678",
            "+91 67801 06821",
            "+91 74249 12035",
            "+91 61279 22799",
            "+91 71970 32458",
            "+91 61279 57837",
            "+91 89172 23395",
            "+91 88472 96746",
            "+91 80799 20281",
            "+91 80798 67267",
            "+91 61279 13408",
            "+91 61279 61330",
            "+91 61279 61771",
            "+91 68011 01961",
            "+91 61279 74439",
            "+91 73196 70881",
            "+91 788 777 8598",
            "+91 61279 66359",
            "+91 61279 19358",
            "+91 89177 08453",
            "+91 67401 45674",
            "+91 61279 84384",
            "+91 61279 16079",
            "+91 88378 40433",
            "+91 99428 62160",
            "+91 75950 01992",
            "+91 61279 77932",
            "+91 65105 56737",
            "+91 61279 18742"
    };

    public static String[] department = new String[]{
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science ",
            "Computer Science "
    };


}
